
---
- name: Create mirrors script
  become: yes
  template:
    src: "{{ item.template }}.j2"
    dest: "{{ item.path }}/{{ item.template }}"
    mode: "{{ item.mode }}"
    group: docker
  with_items:
    - { template: .git-credentials , path: "{{ mirror_home }}", mode: '0644' }
    - { template: .git-config , path: "{{ mirror_home }}", mode: '0644' }
    - { template: install_mirrors.sh , path: "{{ mirror_home }}", mode: '0755' }

- name: Clone the repos
  become: yes
  command: "bash {{ mirror_home }}/install_mirrors.sh"
